### ISSUE TITLE
Error building XPlatCppSdk on Linux

### ISSUE THREAD

**Issue by TheRabid** [PlayFab/XPlatCppSdk#23]
Hello

I'm following the steps described [in the makefile file in here](https://github.com/PlayFab/XPlatCppSdk/blob/master/build/Linux/makefile) to build on Linux, but after installing all that is needed and running the command `make all` I'm getting the following error

```
[...]
g++ -I ../../code -I ../../code/include -I ../../external/aria/lib/include/public -I ../../external/aria/lib -I ../../external/aria/bondlite/include/bond_lite -I ../../external/aria/bondlite/generated -include ../../test/TestApp/TestAppPch.h -D ENABLE_PLAYFABADMIN_API -D ENABLE_PLAYFABSERVER_API -o XPlatSocket.o -c ../../code/source/playfab/QoS/XPlatSocket.cpp
g++ -I ../../code -I ../../code/include -I ../../external/aria/lib/include/public -I ../../external/aria/lib -I ../../external/aria/bondlite/include/bond_lite -I ../../external/aria/bondlite/generated -include ../../test/TestApp/TestAppPch.h -D ENABLE_PLAYFABADMIN_API -D ENABLE_PLAYFABSERVER_API -o main.o -c ../../test/TestApp/TestApp.cpp
../../test/TestApp/TestApp.cpp: In static member function ‘static void PlayFabUnit::TestApp::Log(const char*, ...)’:
../../test/TestApp/TestApp.cpp:118:9: error: ‘_vsnprintf_s’ was not declared in this scope
         _vsnprintf_s(message, sizeof(message), format, args);
         ^~~~~~~~~~~~
../../test/TestApp/TestApp.cpp:118:9: note: suggested alternative: ‘vsnprintf’
         _vsnprintf_s(message, sizeof(message), format, args);
         ^~~~~~~~~~~~
         vsnprintf
make: *** [makefile:125: main.o] Error 1
```

I cannot either follow the steps [in this quickstart guide](https://docs.microsoft.com/es-es/gaming/playfab/sdks/xplatcpp/quickstart-linux) for which [I have already submitted a question](https://community.playfab.com/questions/30432/error-following-linux-c-sdk-first-steps-tutorial-t.html) but with no responses.

Any ideas?

**Comment by Vicodex** [comment]
Hello, our Linux build from makefile is currently broken and we are working on bringing it back, while also refactoring its test application and making it similar to one used in Windows build. The ETA for this is about two weeks.

**Comment by MSFT-Chris-Barrett** [comment]
@Vicodex, is this Linux build issue already resolved?  If so, this is a friendly reminder to close out the issue.  :)
