### ISSUE TITLE
crashed in android ndk game

### ISSUE THREAD

**Issue by vincentely** [PlayFab/XPlatCppSdk#24]
Hello
We build the Playfab with Android NDK(v20)  in native c++ game for Android.
Start to login when the game started.
It crashed in the Function PlayFabAndroidHttpPlugin::Update().
We have log the final crash function is DeleteGlobalRef in the Destructor of RequestImpl.

line 161
PlayFabAndroidHttpPlugin.cpp

        virtual ~RequestImpl()
        {
            if (this->httpRequestObject)
            {
                this->jniEnv->DeleteGlobalRef(this->httpRequestObject);
                this->httpRequestObject = nullptr;
            }
            this->jniEnv = nullptr;
        }

Any ideas?

**Comment by toddbellMSFT** [comment]
Sorry for such a late delay in response. This issue sounds like the httpRequestObject somehow changed between that earlier nullptr if check and that DeleteGlobalRef. 

Question, are you still running into this issue? And when you are building for Android v20, do you mean Android 4.4 KitKat API level 20? I'm having trouble reproducing your issue.

**Comment by toddbellMSFT** [comment]
We have been unable to repro this issue. 

If you are still experiencing a problem, please post on the forums for an expedited response https://community.playfab.com/index.html
