### ISSUE TITLE
Design makes undefined behavior on new platforms not-unlikely

### ISSUE THREAD

**Issue by MSFT-Chris-Barrett** [PlayFab/XPlatCppSdk#33]
https://github.com/PlayFab/XPlatCppSdk/blob/34e48efaba7ecdbebddd68652d70154bf0bb341a/code/include/playfab/PlayFabBaseModel.h#L100

On any/all platforms, `tm timeInfo` will always exist.  Then only on the specified set of platforms, `timeInfo` will have a value assigned to it.  Then any/all platforms will work with the data in `timeInfo`.

Maybe this is the one exceptional place like this, or maybe there are other areas in the PlayFab SDK designed this way.  The issue is when a new platform is added or a user of PlayFab tries to port this to a new platform, this and any other similar areas will build fine, but will cause undefined behavior that may be difficult to track down.  Avoiding undefined behavior relies on people to manually find _every_ instance like this.

Suggest looking for all areas in the PlayFab SDK with this sort of design-- and maybe this is the only one-- and doing one of:
- Only declare/define the object when a value is going to be assigned to it unconditionally.  So, per set of platforms, which is repetitive but safer.
- Have an #else that makes use of #error to notify people when there's a per-platform area of code that needs attention.

**Comment by toddbellMSFT** [comment]
We have been adding platform specific timeInfo code for assigning timeInfo, there should not be a case where we will not assign this object.
