### ISSUE TITLE
PlayFabSettings.h includes itself

### ISSUE THREAD

**Issue by MSFT-Chris-Barrett** [PlayFab/XPlatCppSdk#35]
https://github.com/PlayFab/XPlatCppSdk/blob/34e48efaba7ecdbebddd68652d70154bf0bb341a/code/include/playfab/PlayFabSettings.h#L4

_Might_ be harmless on most/all compilers.

**Comment by toddbellMSFT** [comment]
This has been fixed since the Issue was posted: https://github.com/PlayFab/XPlatCppSdk/blob/master/code/include/playfab/PlayFabSettings.h#L4
